name: 💡 Feature Request
description: Suggest an idea or improvement for HyperBridge
title: "[FEAT] "
labels: ["enhancement"]
assignees:
  - D4vidDf
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your interest in improving HyperBridge!
        Please verify that your idea hasn't already been suggested by searching the existing issues.

  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when I try to dismiss a notification and...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: It would be great if the island could auto-expand when...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: I tried using the existing widget settings, but...
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false
